/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-07-21 07:41:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.customerservicePage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import notice.model.vo.Notice;

public final class customerserviceboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("notice.model.vo.Notice");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");

	Notice notice = (Notice)request.getAttribute("notice");

      out.write("  \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zxx\" class=\"no-js\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<!-- Mobile Specific Meta -->\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("<!-- Favicon-->\n");
      out.write("<link rel=\"shortcut icon\" href=\"img/fav.png\">\n");
      out.write("<!-- Author Meta -->\n");
      out.write("<meta name=\"author\" content=\"CodePixar\">\n");
      out.write("<!-- Meta Description -->\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<!-- Meta Keyword -->\n");
      out.write("<meta name=\"keywords\" content=\"\">\n");
      out.write("<!-- meta character set -->\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<!-- Site Title -->\n");
      out.write("<title>고객센터</title>\n");
      out.write("<script type=\"text/javascript\" src=\"/Shoesgone/resources/js/jquery-3.6.0.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(function(){\n");
      out.write("\t$(\"table *\").css('width','100%');\n");
      out.write("\t$(\"table *\").css('border-top','1px');\n");
      out.write("\t$(\"table *\").css('color','blue');\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("<!--\n");
      out.write("            CSS\n");
      out.write("            ============================================= -->\n");
      out.write("<link rel=\"stylesheet\" href=\"/Shoesgone/resources/css/linearicons.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/Shoesgone/resources/css/owl.carousel.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/Shoesgone/resources/css/themify-icons.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/Shoesgone/resources/css/font-awesome.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/Shoesgone/resources/css/nice-select.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/Shoesgone/resources/css/nouislider.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/Shoesgone/resources/css/bootstrap.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/Shoesgone/resources/css/main.css\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write("#floatdiv {\n");
      out.write("\n");
      out.write("    position:fixed; _position:absolute; _z-index:-1;\n");
      out.write("\n");
      out.write("    width:100px;\n");
      out.write("\n");
      out.write("    display:inline-block;/* overflow:hidden;  같은 의미? */\n");
      out.write("\n");
      out.write("    right:0px; /* //화면 오른쪽에 위치한다. left로 변경가능 */\n");
      out.write("\n");
      out.write("    top:20%; /* //화면 위쪽과의 간격 */\n");
      out.write("\n");
      out.write("    background-color: transparent;\n");
      out.write("\n");
      out.write("    margin:0;\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("#floatdiv ul  { list-style: none; }\n");
      out.write("\n");
      out.write("#floatdiv li  { margin-bottom: 2px; text-align: left; }\n");
      out.write("\n");
      out.write("#floatdiv a   { color: #5D5D5D; border: 0; text-decoration: none; display: float; }\n");
      out.write("\n");
      out.write("#floatdiv a:hover, #floatdiv .menu  { background-color: #5D5D5D; color: #fff; } /* 마우스오버 시 배경/글씨 색깔 */\n");
      out.write("\n");
      out.write("#floatdiv .menu, #floatdiv .last    { margin-bottom: 0px; }\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("#floatContent {\n");
      out.write("\n");
      out.write("    padding:5px;\n");
      out.write("\n");
      out.write("border-width: 2px;\n");
      out.write("\n");
      out.write("border-color: #7f7f7f;\n");
      out.write("\n");
      out.write("border-style: solid;\n");
      out.write("\n");
      out.write("border-bottom-left-radius: 10px;\n");
      out.write("\n");
      out.write("border-bottom-right-radius: 10px;\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("#floatTitle {\n");
      out.write("\n");
      out.write("width:100px;\n");
      out.write("\n");
      out.write("height:30px;\n");
      out.write("\n");
      out.write("line-height:30px;\n");
      out.write("\n");
      out.write("background-color: #7f7f7f;\n");
      out.write("\n");
      out.write("/* 텍스트 */\n");
      out.write("\n");
      out.write("color: #fff;\n");
      out.write("\n");
      out.write("text-align: center;\n");
      out.write("\n");
      out.write("text-decoration: none;\n");
      out.write("\n");
      out.write("font-weight:bold;\n");
      out.write("\n");
      out.write("font-size:12px;\n");
      out.write("\n");
      out.write("/* 모양 */\n");
      out.write("\n");
      out.write("border-top-left-radius: 10px;\n");
      out.write("\n");
      out.write("border-top-right-radius: 10px;\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("}\n");
      out.write(".sub_news{\n");
      out.write(" font-size: 16px;\n");
      out.write("\n");
      out.write(" \n");
      out.write("}\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<!-- Start Header Area -->\n");
      out.write("\t<header class=\"header_area sticky-header\">\n");
      out.write("\t\t<div class=\"main_menu\">\n");
      out.write("\t\t\t<nav class=\"navbar navbar-expand-lg navbar-light main_box\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand logo_h\" href=\"index.html\"><img\n");
      out.write("\t\t\t\t\t\tsrc=\"img/logo.png\" alt=\"\"></a>\n");
      out.write("\t\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("\t\t\t\t\t\tdata-target=\"#navbarSupportedContent\"\n");
      out.write("\t\t\t\t\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("\t\t\t\t\t\taria-label=\"Toggle navigation\">\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("\t\t\t\t\t<div class=\"collapse navbar-collapse offset\"\n");
      out.write("\t\t\t\t\t\tid=\"navbarSupportedContent\">\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav navbar-nav menu_nav ml-auto\">\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.html\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item submenu dropdown\"><a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\"\n");
      out.write("\t\t\t\t\t\t\t\trole=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Shop</a>\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"category.html\">Shop Category</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"single-product.html\">Product Details</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"checkout.html\">Product Checkout</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"cart.html\">Shopping\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tCart</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"confirmation.html\">Confirmation</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item submenu dropdown\"><a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\"\n");
      out.write("\t\t\t\t\t\t\t\trole=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Blog</a>\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"blog.html\">Blog</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"single-blog.html\">Blog Details</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item submenu dropdown\"><a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\"\n");
      out.write("\t\t\t\t\t\t\t\trole=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Pages</a>\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"login.html\">Login</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"tracking.html\">Tracking</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"elements.html\">Elements</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\t\thref=\"contact.html\">Contact</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a href=\"#\" class=\"cart\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"ti-bag\"></span></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"search\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"lnr lnr-magnifier\" id=\"search\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"search_input\" id=\"search_input_box\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<form class=\"d-flex justify-content-between\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"search_input\"\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Search Here\">\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn\"></button>\n");
      out.write("\t\t\t\t\t<span class=\"lnr lnr-cross\" id=\"close_search\" title=\"Close Search\"></span>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>\n");
      out.write("\t<!-- End Header Area -->\n");
      out.write("\n");
      out.write("\t<!-- Start Banner Area -->\n");
      out.write("\t<section class=\"banner-area organic-breadcrumb\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div\n");
      out.write("\t\t\t\tclass=\"breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end\">\n");
      out.write("\t\t\t\t<div class=\"col-first\">\n");
      out.write("\t\t\t\t\t<h1>CustomerSerive</h1>\n");
      out.write("\t\t\t\t\t<nav class=\"d-flex align-items-center\">\n");
      out.write("\t\t\t\t\t\t<a href=\"index.html\">Home<span class=\"lnr lnr-arrow-right\"></span></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"category.html\">CustomerSerive</a>\n");
      out.write("\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\t<!--================Contact Area =================-->\n");
      out.write("\t<section><br><br><br>\n");
      out.write("\t<h2 align=\"center\">고객센터</h2><hr>\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<table class=\"table table-striped\" style=\"text-align: center; border: 1px solid #dddddd\">\n");
      out.write("\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<th colspan=\"2\" style=\"background-color: #eeeeee; text-align: center;\">상세보기</th>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</thead>\n");
      out.write("\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 20%;\">글 제목</td>\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" style=\"text-align: left;\">");
      out.print( notice.getNoticeTitle() );
      out.write("</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td>작성자</td>\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" style=\"text-align: left;\">");
      out.print( notice.getNoticeWriter() );
      out.write("</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td>작성일자</td>\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" style=\"text-align: left;\">");
      out.print( notice.getNoticeDate() );
      out.write("</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td>내용</td>\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" style=\"height: 200px; text-align: left;\">");
      out.print( notice.getNoticeContent() );
      out.write("</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</tbody>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\n");
      out.write("\t\t\t<!-- 해당 글의 작성자가 본인이라면 수정과 삭제가 가능하도록 코드 추가 -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write(" <br>\t\n");
      out.write("\t\t\t<center><button onclick=\"javascript:history.go(-1);\" class=\"genric-btn primary\">목록</button></a></center><br><br>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\t\t\t<div id=\"floatdiv\">\n");
      out.write("\n");
      out.write("<div id=\"floatTitle\">상담채널</div>\n");
      out.write("\n");
      out.write("<div id=\"floatContent\">\n");
      out.write("\n");
      out.write("<ul>\n");
      out.write("\n");
      out.write("<li>\n");
      out.write("\n");
      out.write("<img src=\"/Shoesgone/resources/img/kakach.png\" width = \"80px\"><a href=\"#\"></a>\n");
      out.write("\n");
      out.write("</li>\n");
      out.write("\n");
      out.write("<li>\n");
      out.write("\n");
      out.write("<img src=\"/Shoesgone/resources/img/chatbot.jpg\" width = \"80px\"><a href=\"#\"></a>\n");
      out.write("\n");
      out.write("</li>\n");
      out.write("\n");
      out.write("</ul>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- //floatMenu -->\n");
      out.write("\t\t</section>\n");
      out.write("\t\t<!--================Contact Area =================-->\n");
      out.write("\n");
      out.write("\t\t<!-- start footer Area -->\n");
      out.write("\t\t<footer class=\"footer-area section_gap\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3  col-md-6 col-sm-6\">\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer-widget\">\n");
      out.write("\t\t\t\t\t\t\t<h6>About Us</h6>\n");
      out.write("\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,\n");
      out.write("\t\t\t\t\t\t\t\tsed do eiusmod tempor incididunt ut labore dolore magna aliqua.\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4  col-md-6 col-sm-6\">\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer-widget\">\n");
      out.write("\t\t\t\t\t\t\t<h6>Newsletter</h6>\n");
      out.write("\t\t\t\t\t\t\t<p>Stay update with our latest</p>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"\" id=\"mc_embed_signup\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<form target=\"_blank\" novalidate=\"true\"\n");
      out.write("\t\t\t\t\t\t\t\t\taction=\"https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01\"\n");
      out.write("\t\t\t\t\t\t\t\t\tmethod=\"get\" class=\"form-inline\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"d-flex flex-row\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" name=\"EMAIL\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Enter Email\" onfocus=\"this.placeholder = ''\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonblur=\"this.placeholder = 'Enter Email '\" required=\"\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"email\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button class=\"click-btn btn btn-default\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"position: absolute; left: -5000px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"b_36c4fd991d266f23781ded980_aefe40901a\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttabindex=\"-1\" value=\"\" type=\"text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <div class=\"col-lg-4 col-md-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"bb-btn btn\"><span class=\"lnr lnr-arrow-right\"></span></button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>  -->\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"info\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3  col-md-6 col-sm-6\">\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer-widget mail-chimp\">\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"mb-20\">Instragram Feed</h6>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"instafeed d-flex flex-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"img/i1.jpg\" alt=\"\"></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"img/i2.jpg\" alt=\"\"></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"img/i3.jpg\" alt=\"\"></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"img/i4.jpg\" alt=\"\"></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"img/i5.jpg\" alt=\"\"></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"img/i6.jpg\" alt=\"\"></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"img/i7.jpg\" alt=\"\"></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"img/i8.jpg\" alt=\"\"></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-2 col-md-6 col-sm-6\">\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer-widget\">\n");
      out.write("\t\t\t\t\t\t\t<h6>Follow Us</h6>\n");
      out.write("\t\t\t\t\t\t\t<p>Let us be social</p>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer-social d-flex align-items-center\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-facebook\"></i></a> <a href=\"#\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-twitter\"></i></a> <a href=\"#\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-dribbble\"></i></a> <a href=\"#\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-behance\"></i></a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div\n");
      out.write("\t\t\t\t\tclass=\"footer-bottom d-flex justify-content-center align-items-center flex-wrap\">\n");
      out.write("\t\t\t\t\t<p class=\"footer-text m-0\">\n");
      out.write("\t\t\t\t\t\t<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("\t\t\t\t\t\tCopyright &copy;\n");
      out.write("\t\t\t\t\t\t<script>\n");
      out.write("\t\t\t\t\t\t\tdocument.write(new Date().getFullYear());\n");
      out.write("\t\t\t\t\t\t</script>\n");
      out.write("\t\t\t\t\t\tAll rights reserved | This template is made with <i\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a\n");
      out.write("\t\t\t\t\t\t\thref=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\n");
      out.write("\t\t\t\t\t\t<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</footer>\n");
      out.write("\t\t<!-- End footer Area -->\n");
      out.write("\n");
      out.write("\t\t<!--================Contact Success and Error message Area =================-->\n");
      out.write("\t\t<div id=\"success\" class=\"modal modal-message fade\" role=\"dialog\">\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Close\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-close\"></i>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t<h2>Thank you</h2>\n");
      out.write("\t\t\t\t\t\t<p>Your message is successfully sent...</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<!-- Modals error -->\n");
      out.write("\n");
      out.write("\t\t<div id=\"error\" class=\"modal modal-message fade\" role=\"dialog\">\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Close\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-close\"></i>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t<h2>Sorry !</h2>\n");
      out.write("\t\t\t\t\t\t<p>Something went wrong</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--================End Contact Success and Error message Area =================-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/vendor/jquery-2.2.4.min.js\"></script>\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js\" integrity=\"sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4\"\n");
      out.write("\t crossorigin=\"anonymous\"></script>\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/vendor/bootstrap.min.js\"></script>\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/jquery.ajaxchimp.min.js\"></script>\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/jquery.nice-select.min.js\"></script>\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/jquery.sticky.js\"></script>\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/nouislider.min.js\"></script>\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/owl.carousel.min.js\"></script>\n");
      out.write("\t<!--gmaps Js-->\n");
      out.write("\t<script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE\"></script>\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/gmaps.min.js\"></script>\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
