/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-07-21 08:48:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.customerservicePage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class customerwriteView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zxx\" class=\"no-js\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\t<!-- Mobile Specific Meta -->\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("\t<!-- Favicon-->\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"img/fav.png\">\n");
      out.write("\t<!-- Author Meta -->\n");
      out.write("\t<meta name=\"author\" content=\"CodePixar\">\n");
      out.write("\t<!-- Meta Description -->\n");
      out.write("\t<meta name=\"description\" content=\"\">\n");
      out.write("\t<!-- Meta Keyword -->\n");
      out.write("\t<meta name=\"keywords\" content=\"\">\n");
      out.write("\t<!-- meta character set -->\n");
      out.write("\t<meta charset=\"UTF-8\">\n");
      out.write("\t<!-- Site Title -->\n");
      out.write("\t<title>주문상세보기</title>\n");
      out.write("\t<!--\n");
      out.write("            CSS\n");
      out.write("            ============================================= -->\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/Shoesgone/resources/css/linearicons.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/Shoesgone/resources/css/owl.carousel.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/Shoesgone/resources/css/themify-icons.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/Shoesgone/resources/css/font-awesome.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/Shoesgone/resources/css/nice-select.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/Shoesgone/resources/css/nouislider.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/Shoesgone/resources/css/bootstrap.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/Shoesgone/resources/css/main.css\">\n");
      out.write("\t<style type=\"text/css\">\n");
      out.write("\t.orderdetail{\n");
      out.write("\talign : center;\n");
      out.write("\t}\n");
      out.write(".th{\n");
      out.write(" text-align : center;\n");
      out.write("}\n");
      out.write(".page_wrap {\n");
      out.write("\ttext-align:center;\n");
      out.write("\tfont-size:0;\n");
      out.write(" }\n");
      out.write(".page_nation {\n");
      out.write("\tdisplay:inline-block;\n");
      out.write("}\n");
      out.write(".page_nation .none {\n");
      out.write("\tdisplay:none;\n");
      out.write("}\n");
      out.write(".page_nation a {\n");
      out.write("\tdisplay:block;\n");
      out.write("\tmargin:0 3px;\n");
      out.write("\tfloat:left;\n");
      out.write("\tborder:1px solid #e6e6e6;\n");
      out.write("\twidth:28px;\n");
      out.write("\theight:28px;\n");
      out.write("\tline-height:28px;\n");
      out.write("\ttext-align:center;\n");
      out.write("\tbackground-color:#fff;\n");
      out.write("\tfont-size:13px;\n");
      out.write("\tcolor:#999999;\n");
      out.write("\ttext-decoration:none;\n");
      out.write("}\n");
      out.write(".page_nation .arrow {\n");
      out.write("\tborder:1px solid #ccc;\n");
      out.write("}\n");
      out.write(".page_nation .pprev {\n");
      out.write("\tbackground:#f8f8f8 url('img/page_pprev.png') no-repeat center center;\n");
      out.write("\tmargin-left:0;\n");
      out.write("}\n");
      out.write(".page_nation .prev {\n");
      out.write("\tbackground:#f8f8f8 url('img/page_prev.png') no-repeat center center;\n");
      out.write("\tmargin-right:7px;\n");
      out.write("}\n");
      out.write(".page_nation .next {\n");
      out.write("\tbackground:#f8f8f8 url('img/page_next.png') no-repeat center center;\n");
      out.write("\tmargin-left:7px;\n");
      out.write("}\n");
      out.write(".page_nation .nnext {\n");
      out.write("\tbackground:#f8f8f8 url('img/page_nnext.png') no-repeat center center;\n");
      out.write("\tmargin-right:0;\n");
      out.write("}\n");
      out.write(".page_nation a.active {\n");
      out.write("\tbackground-color:#42454c;\n");
      out.write("\tcolor:#fff;\n");
      out.write("\tborder:1px solid #42454c;\n");
      out.write("}\n");
      out.write("\t</style>\n");
      out.write("\t\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<!-- Start Header Area -->\n");
      out.write("\t<header class=\"header_area sticky-header\">\n");
      out.write("\t\t<div class=\"main_menu\">\n");
      out.write("\t\t\t<nav class=\"navbar navbar-expand-lg navbar-light main_box\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand logo_h\" href=\"index.html\"><img src=\"img/logo.png\" alt=\"\"></a>\n");
      out.write("\t\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\n");
      out.write("\t\t\t\t\t aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("\t\t\t\t\t<div class=\"collapse navbar-collapse offset\" id=\"navbarSupportedContent\">\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav navbar-nav menu_nav ml-auto\">\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.html\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item submenu dropdown\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\n");
      out.write("\t\t\t\t\t\t\t\t aria-expanded=\"false\">Shop</a>\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"category.html\">Shop Category</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"single-product.html\">Product Details</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"checkout.html\">Product Checkout</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"cart.html\">Shopping Cart</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"confirmation.html\">Confirmation</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item submenu dropdown\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\n");
      out.write("\t\t\t\t\t\t\t\t aria-expanded=\"false\">Blog</a>\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"blog.html\">Blog</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"single-blog.html\">Blog Details</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item submenu dropdown\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\n");
      out.write("\t\t\t\t\t\t\t\t aria-expanded=\"false\">Pages</a>\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"login.html\">Login</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"tracking.html\">Tracking</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"elements.html\">Elements</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\" href=\"contact.html\">Contact</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a href=\"#\" class=\"cart\"><span class=\"ti-bag\"></span></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"search\"><span class=\"lnr lnr-magnifier\" id=\"search\"></span></button>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"search_input\" id=\"search_input_box\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<form class=\"d-flex justify-content-between\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"search_input\" placeholder=\"Search Here\">\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn\"></button>\n");
      out.write("\t\t\t\t\t<span class=\"lnr lnr-cross\" id=\"close_search\" title=\"Close Search\"></span>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>\n");
      out.write("\t<!-- End Header Area -->\n");
      out.write("\n");
      out.write("\t<!-- Start Banner Area -->\n");
      out.write("\t<section class=\"banner-area organic-breadcrumb\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end\">\n");
      out.write("\t\t\t\t<div class=\"col-first\">\n");
      out.write("\t\t\t\t\t<h1>Mypage</h1>\n");
      out.write("\t\t\t\t\t<nav class=\"d-flex align-items-center\">\n");
      out.write("\t\t\t\t\t\t<a href=\"index.html\">Home<span class=\"lnr lnr-arrow-right\"></span></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"category.html\">Mypage</a>\n");
      out.write("\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t\n");
      out.write("\t<!--================Contact Area =================-->\n");
      out.write("\t<section><br><br><br>\n");
      out.write("\t\t<article>\n");
      out.write("\n");
      out.write("\t\t<div class=\"container\" role=\"main\">\n");
      out.write("\n");
      out.write("\t\t\t<h2>1:1문의</h2>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"row\" >\n");
      out.write("\t\t\t<form method=\"post\" action=\"writeAction.jsp\" >\n");
      out.write("\t\t\t\t<table class=\"table table-striped\" style=\"text-align: center; border: 1px solid #dddddd; width: 1000px;\" >\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<th colspan=\"2\" style=\"background-color: #eeeeee; text-align: center;\">게시판 글쓰기 양식</th>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" placeholder=\"글 제목\" name=\"questionTitle\" maxlength=\"50\" style=\"width:950px ;\"></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td><textarea class=\"form-control\" placeholder=\"글 내용\" name=\"questionContent\" maxlength=\"2048\" style=\"width:950px ;height: 350px;\"></textarea></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t\t<!-- 글쓰기 버튼 생성 -->\n");
      out.write("\t\t\t\t<center>\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"genric-btn primary small\" id=\"btnSave\">저장</button>\n");
      out.write("\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"genric-btn primary small\" id=\"btnList\">목록</button>\n");
      out.write("</center>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\t\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div><br><br><br>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</article>\n");
      out.write("\n");
      out.write("\n");
      out.write("  \n");
      out.write("</section>\n");
      out.write("\t<!--================Contact Area =================-->\n");
      out.write("\n");
      out.write("\t<!-- start footer Area -->\n");
      out.write("\t<footer class=\"footer-area section_gap\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-3  col-md-6 col-sm-6\">\n");
      out.write("\t\t\t\t\t<div class=\"single-footer-widget\">\n");
      out.write("\t\t\t\t\t\t<h6>About Us</h6>\n");
      out.write("\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\tLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore\n");
      out.write("\t\t\t\t\t\t\tmagna aliqua.\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-4  col-md-6 col-sm-6\">\n");
      out.write("\t\t\t\t\t<div class=\"single-footer-widget\">\n");
      out.write("\t\t\t\t\t\t<h6>Newsletter</h6>\n");
      out.write("\t\t\t\t\t\t<p>Stay update with our latest</p>\n");
      out.write("\t\t\t\t\t\t<div class=\"\" id=\"mc_embed_signup\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<form target=\"_blank\" novalidate=\"true\" action=\"https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01\"\n");
      out.write("\t\t\t\t\t\t\t method=\"get\" class=\"form-inline\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex flex-row\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"form-control\" name=\"EMAIL\" placeholder=\"Enter Email\" onfocus=\"this.placeholder = ''\" onblur=\"this.placeholder = 'Enter Email '\"\n");
      out.write("\t\t\t\t\t\t\t\t\t required=\"\" type=\"email\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"click-btn btn btn-default\"><i class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></i></button>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"position: absolute; left: -5000px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input name=\"b_36c4fd991d266f23781ded980_aefe40901a\" tabindex=\"-1\" value=\"\" type=\"text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- <div class=\"col-lg-4 col-md-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"bb-btn btn\"><span class=\"lnr lnr-arrow-right\"></span></button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>  -->\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"info\"></div>\n");
      out.write("\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-3  col-md-6 col-sm-6\">\n");
      out.write("\t\t\t\t\t<div class=\"single-footer-widget mail-chimp\">\n");
      out.write("\t\t\t\t\t\t<h6 class=\"mb-20\">Instragram Feed</h6>\n");
      out.write("\t\t\t\t\t\t<ul class=\"instafeed d-flex flex-wrap\">\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"img/i1.jpg\" alt=\"\"></li>\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"img/i2.jpg\" alt=\"\"></li>\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"img/i3.jpg\" alt=\"\"></li>\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"img/i4.jpg\" alt=\"\"></li>\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"img/i5.jpg\" alt=\"\"></li>\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"img/i6.jpg\" alt=\"\"></li>\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"img/i7.jpg\" alt=\"\"></li>\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"img/i8.jpg\" alt=\"\"></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-2 col-md-6 col-sm-6\">\n");
      out.write("\t\t\t\t\t<div class=\"single-footer-widget\">\n");
      out.write("\t\t\t\t\t\t<h6>Follow Us</h6>\n");
      out.write("\t\t\t\t\t\t<p>Let us be social</p>\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-social d-flex align-items-center\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-dribbble\"></i></a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-behance\"></i></a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"footer-bottom d-flex justify-content-center align-items-center flex-wrap\">\n");
      out.write("\t\t\t\t<p class=\"footer-text m-0\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("\t<!-- End footer Area -->\n");
      out.write("\n");
      out.write("\t<!--================Contact Success and Error message Area =================-->\n");
      out.write("\t<div id=\"success\" class=\"modal modal-message fade\" role=\"dialog\">\n");
      out.write("\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-close\"></i>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t<h2>Thank you</h2>\n");
      out.write("\t\t\t\t\t<p>Your message is successfully sent...</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- Modals error -->\n");
      out.write("\n");
      out.write("\t<div id=\"error\" class=\"modal modal-message fade\" role=\"dialog\">\n");
      out.write("\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-close\"></i>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t<h2>Sorry !</h2>\n");
      out.write("\t\t\t\t\t<p> Something went wrong </p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!--================End Contact Success and Error message Area =================-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<script src=\"/Shoesgone/resources/js/vendor/jquery-2.2.4.min.js\"></script>\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js\" integrity=\"sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4\"\n");
      out.write("\t crossorigin=\"anonymous\"></script>\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/vendor/bootstrap.min.js\"></script>\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/jquery.ajaxchimp.min.js\"></script>\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/jquery.nice-select.min.js\"></script>\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/jquery.sticky.js\"></script>\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/nouislider.min.js\"></script>\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/owl.carousel.min.js\"></script>\n");
      out.write("\t<!--gmaps Js-->\n");
      out.write("\t<script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE\"></script>\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/gmaps.min.js\"></script>\n");
      out.write("\t<script src=\"/Shoesgone/resources/js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
