/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-07-21 02:47:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import board.model.vo.Board;
import java.sql.Date;

public final class boardListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("board.model.vo.Board");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.sql.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

	ArrayList<Board> list = (ArrayList<Board>)request.getAttribute("list");
	int listCount = ((Integer)request.getAttribute("listCount")).intValue();
	int startPage = ((Integer)request.getAttribute("startPage")).intValue();
	int endPage = ((Integer)request.getAttribute("endPage")).intValue();
	int maxPage = ((Integer)request.getAttribute("maxPage")).intValue();
	int currentPage = ((Integer)request.getAttribute("currentPage")).intValue();

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>first</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function showWriteForm(){\r\n");
      out.write("\tlocation.href = \"/first/cons/board/boardWriteForm.jsp\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<h2 align=\"center\">총 게시글 갯수 : ");
      out.print( listCount );
      out.write("</h2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"align:center;text-align:center;\">\r\n");
      out.write("\t<button onclick=\"showWriteForm();\">글쓰기</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<table align=\"center\" border=\"1\" cellspacing=\"0\" width=\"700\">\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th>번호</th>\r\n");
      out.write("\t<th>제목</th>\r\n");
      out.write("\t<th>작성자</th>\r\n");
      out.write("\t<th>날짜</th>\r\n");
      out.write("\t<th>첨부파일</th>\r\n");
      out.write("\t<th>조회수</th>\r\n");
      out.write("</tr>\r\n");
 for(Board b : list){ 
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th>");
      out.print( b.getBoardNum() );
      out.write("</th>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t\t");
 if(b.getBoardLevel() == 2){  //원글의 댓글일 때 
      out.write("\r\n");
      out.write("\t\t&nbsp; &nbsp; ▶ \r\n");
      out.write("\t\t");
 }else if(b.getBoardLevel() == 3){ //대댓글일 때 
      out.write("\r\n");
      out.write("\t\t&nbsp; &nbsp; &nbsp; &nbsp; ▶▶\r\n");
      out.write("\t\t");
 } 
      out.write(" \r\n");
      out.write("\t\t<a href=\"/first/bdetail?bnum=");
      out.print( b.getBoardNum() );
      out.write("&page=");
      out.print( currentPage );
      out.write('"');
      out.write('>');
      out.print( b.getBoardTitle() );
      out.write("</a>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t<td align=\"center\">");
      out.print( b.getBoardWriter() );
      out.write("</td>\r\n");
      out.write("\t<td align=\"center\">");
      out.print( b.getBoardDate() );
      out.write("</td>\r\n");
      out.write("\t<td align=\"center\">\r\n");
      out.write("\t\t");
 if(b.getBoardOriginalFilename() != null){ 
      out.write("\r\n");
      out.write("\t\t\t◎\r\n");
      out.write("\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t&nbsp;\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("\t<td align=\"right\">");
      out.print( b.getBoardReadCount() );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
 } //list : for each 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("\t");
 if(currentPage <= 1){ 
      out.write("\r\n");
      out.write("\t\t[맨처음] &nbsp;\r\n");
      out.write("\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t<a href=\"/first/blist?page=1\">[맨처음]</a> &nbsp;\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\t<!-- 이전 페이지 그룹으로 이동 -->\r\n");
      out.write("\t");
 if((currentPage - 10) < startPage && 
			(currentPage - 10) > 1){ 
      out.write("\r\n");
      out.write("\t\t<a href=\"/first/blist?page=");
      out.print( startPage - 10 );
      out.write("\">[이전그룹]</a> &nbsp;\r\n");
      out.write("\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t[이전그룹] &nbsp;\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 현재 페이지 그룹의 페이지 숫자 출력 -->\r\n");
      out.write("\t");
 for(int p = startPage; p <= endPage; p++){ 
			if(p == currentPage){
	
      out.write("\r\n");
      out.write("\t\t <font color=\"red\" size=\"4\"><b>[");
      out.print( p );
      out.write("]</b></font>\r\n");
      out.write("\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t<a href=\"/first/blist?page=");
      out.print( p );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\r\n");
      out.write("\t");
 }} 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 다음 페이지 그룹으로 이동 -->\r\n");
      out.write("\t");
 if((currentPage + 10) > endPage && 
			(currentPage + 10) < maxPage){ 
      out.write("\r\n");
      out.write("\t\t<a href=\"/first/blist?page=");
      out.print( endPage + 10 );
      out.write("\">[다음그룹]</a> &nbsp;\r\n");
      out.write("\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t[다음그룹] &nbsp;\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
 if(currentPage >= maxPage){ 
      out.write("\r\n");
      out.write("\t\t[맨끝] &nbsp;\r\n");
      out.write("\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t<a href=\"/first/blist?page=");
      out.print( maxPage );
      out.write("\">[맨끝]</a> &nbsp;\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
